# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_text', models.CharField(max_length=5000)),
                ('blog_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
