# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200)),
                ('comment_text', models.CharField(max_length=5000)),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_comments',
            field=models.ManyToManyField(to='App.Comment'),
        ),
    ]
